### PR TITLE
Wait for the requested response

### PR DESCRIPTION
**Pull request by andreas-amlabs**
When sending a telnet request and at the same time
using the remote control the reponse was sometimes
incorrect. This solution is probably not 100%

Eg. sending main.volume? while fibbling with the remote
does not guarantee that the response is for the
main.volume? command, it could be a response
from remote control volume changes. But filtering
should work for e.g. main.power? while pressing
vol+/- on the remote

Tested within home-assistant

### CODE REVIEW

**Comment by andreas-amlabs** [comment]
I expect this to be the final version ...

**Comment by joopert** [comment]
When something goes wrong, and the receiver does not response correctly, the loop will be infinite. I suppose we need to have a timeout (or a max retry mechanism) which will raise an error. Not sure yet what the best solution is though.

**Comment by andreas-amlabs** [comment]
Sloppy me, read the doc like "will raise timeout exception" ...
Will submit an update later this evening. I feel "raise" should
be enough, lets not overwork it. Even retry could eventually fail, let
the app handle it

**Comment by andreas-amlabs** [comment]
Hope this will fix any issues. Tested it with home-assistant and
appears to work. Difficult to really trigger all mishaps though

**Comment by andreas-amlabs** [comment]
Yeah, I will need to do 1 more patch since e.g. home-assistant does not
like it when there is a raise in __init__. 

Thanks for understanding

**Comment by joopert** [comment]
Uploaded version 0.0.11 to pypi

**Pull request merged**
