### PR TITLE
Transports

### PR DESCRIPTION
**Pull request by gladhorn**
Introduce transports
    
    The rs232 code and telnet are basically the same. The official NAD
    documentation confirms this, the data sent must be identical for both
    protocols.
    Abstract the difference away in simple classes instead of having
    duplicate code.
    
    The TCP class looks sufficiently different, since I cannot test that, I
    do not dare touching it.
    
    This also fixes the need for a 0.5 second wait in the serial port
    connection by rather reading until a '\r' is received.
    Works more reliably for my receiver and I assume all models.
    
    Add a first test to be able to verify different device's protocols.

### CODE REVIEW

**Comment by andreas-amlabs** [comment]
I like the idea !

BUT

the patch does not work as the following code
-----------------
from nad_receiver import *
print("Open nad.inet")
receiver = NADReceiverTelnet("nad.inet")
if receiver:
        print("Test power: ", receiver.main_power('?'))
        print("Test power: ", receiver.main_power('?'))
        print("Test power: ", receiver.main_power('?'))
        print("Test power: ", receiver.main_power('?'))
        print("Test volume: ", receiver.main_volume('?'))
        print("Test volume: ", receiver.main_volume('?'))
        print("Test volume: ", receiver.main_volume('?'))
        print("Test volume: ", receiver.main_volume('?'))
-----------------

Gives this output:

Open nad.inet
Test power:  T787
Test power:  On
Test power:  On
Test power:  On
Test volume:  None
Test volume:  None
Test volume:  None
Test volume:  None

Indicating that you did not consider all of the comments on the NADTelnet section (something like
some firmwares .... blah, blah, blah)

Master gives

Open nad.inet
Test power:  On
Test power:  On
Test power:  On
Test power:  On
Test volume:  None
Test volume:  None
Test volume:  None
Test volume:  None


Which of course is ALSO wrong
Volume broke here: 9b7988cdceee9e7a43b5de1ae1dcf264395a0013  (adding "round")
Probably since
            self.exec_command('main', 'volume', operator, value)
  returns a string
  which makes this logic 'interesting'
            res = int(round(
                self.exec_command('main', 'volume', operator, value)))

-2 Now, but please fix at least your error

**Comment by andreas-amlabs** [comment]
So sorry for the bad HTML above !

**Comment by gladhorn** [comment]
Hi there :) Awesome that you can test telnet, I don't have a device that supports that. I do have trouble with the volume stuff, since my amp only supports setting it, but not getting it. Let's get things cleaned up.

**Comment by gladhorn** [comment]
Right, that round thing was wrong, since the order of the functions got mixed up by the author, let's also fix that!

**Comment by gladhorn** [comment]
OK, the volume should be fixed here: https://github.com/joopert/nad_receiver/pull/26

**Comment by gladhorn** [comment]
@andreas-amlabs could you test again? And maybe also the fix for volume (in my master branch or here: https://github.com/joopert/nad_receiver/pull/26/commits/596f7c9641727cec855c4d3eaf89a20399a5133b

**Comment by andreas-amlabs** [comment]
Hi

This seems to work much better ! +2 :)

We are few users, but we appreciate your work !
@joopert These 2 patches seems to work fine for the Telnet API

Thanks!
Please ping me if you need me to test something more
/A

I found one bug, but I do think that was there before. The NAD Telnet API is really bad
E.g. while the NAD boots, start sending telnet commands to it
the output could be something like

Open nad.inet
Test power:  On
Test power:  0
Main.Power
Test power:  0
Audyssey.Level.User2Right
Test power:  0
Audyssey.Distance.User1Left
Test volume:  -68.0
Test volume:  -68.0
Test volume:  -68.0
Test volume:  -68.0

When expected is 
Open nad.inet
Test power:  On
Test power:  On
Test power:  On
Test power:  On
Test volume:  -68.0
Test volume:  -68.0
Test volume:  -68.0
Test volume:  -68.0

**Comment by joopert** [comment]
Thanks for your effort guys. I will test it on my system as well (rs232), hopefully I can merge it quickly.

**Comment by joopert** [comment]
Thanks again @gladhorn

**Pull request merged**
