### PR TITLE
Added support for the NAD D 7050 amplifier

### PR DESCRIPTION
**Pull request by mwsluis**

### CODE REVIEW

**Comment by joopert** [comment]
Thanks for your PR, and sorry it took a few days.
A few questions / suggestions:

- Do you know if the same codes (like CMD*) are used for other receivers? Can we make this more generic then only for the D7050? The class name should then also be renamed to a more generic name.

- line 159/160 except ConnectionError: return, I think you shouldn't catch the error, because now if a command fails, it just returns nothing. So a program using this lib is not able to determine if the command succeeded or not and whether it should retry to execute the command or not. 

- For the sources, on my own receiver I am able to rename the source names, are you as well? Because then you don't want the names hardcoded.

- Why do you need a sleep? Because it means you will have to wait a second at least before you can send another command. So if you press volume up 10 times, you will have to wait at least 10 seconds before it has reached the volume you want.

**Comment by mwsluis** [comment]
Hi thanks for the feedback, appreciate it as im still learning. 

1. As far as I know only the D7050 (of the amps in its range, d1050, d3020 and d7050) only the 7050 is controllable via ethernet (the 7050 is marketed as ‘controllable via iOS app, the rest aren’t). I agree it would be nicest to integrate the two classes some way, using the same functions. 
2. You’re right. I copied the function from the update function in my hass component. I should throw an error here and catch it in the hass component.
3. The d7050 has fixed inputs and input names. Can’t rename them.
4. Good question. This is my first attempt at using socket, and sleep was my solution to waiting for the amp to build a reply. When I called recv() immediately the amp wouldn’t have a complete reply ready. However, now I’m using a while loop and call recv() until I have the complete reply, it could be I don’t need sleep anymore. I did a lot of testing with this and sometimes if I didn’t use sleep the amp would refuse new connections. I should try to make it work without sleep.

**Comment by mwsluis** [comment]
Latest commit removes try block and sleep calls. With the while loop around recv() I didn't need sleep anymore. I think I'll add a timeout in the while loop next so it won't loop indefinitely when the amp doesn't reply.

**Comment by joopert** [comment]
@mwsluis I still suggest we rename the class to something more generic, then in the future when someone else comes along to add support for another receiver, we can just improve the class without renaming it. 

Apart from that I think it's ready to merge :+1:

**Comment by mwsluis** [comment]
How about receiver_remote or amp_remote, or pyAmp maybe? 
With these latest commits I think the code is ready to merge. If you're ok with it that'd be great :)

**Comment by joopert** [comment]
Are you talking about the library name? I was talking about the class name D7050 :stuck_out_tongue: 
I think this library is only for NAD receivers, but I thought renaming the D7050 class to something like, TCPReceiver or something. Otherwise we might get 1 class per model, I prefer to have 1 class only.

**Comment by mwsluis** [comment]
Okay I renamed the class to NADReceiverTCP.

**Comment by mwsluis** [comment]
Ok I think the code is ready for merging now. It is much more robust in dealing with connection errors and the amp's reply buffer. I tested it with my hass component and it's working great.

**Comment by joopert** [comment]
Thanks, I'll merge and create a new release!

**Pull request merged**
